-- Registro Pirulo: base de datos compartida y privada
create table if not exists public.registros (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  type text not null check (type in ('hotel','teatro','restaurante','contacto','ciudad')),
  name text not null,
  city text default '',
  phone text default '',
  address text default '',
  contact text default '',
  rating text default '',
  favorite boolean not null default false,
  notes text default '',
  created_at timestamptz not null default now()
);

alter table public.registros enable row level security;

drop policy if exists "Usuarios autenticados pueden ver registros" on public.registros;
create policy "Usuarios autenticados pueden ver registros"
on public.registros for select
to authenticated
using (true);

drop policy if exists "Usuarios autenticados pueden crear sus registros" on public.registros;
create policy "Usuarios autenticados pueden crear sus registros"
on public.registros for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "Usuarios autenticados pueden editar registros" on public.registros;
create policy "Usuarios autenticados pueden editar registros"
on public.registros for update
to authenticated
using (true)
with check (true);

drop policy if exists "Usuarios autenticados pueden eliminar registros" on public.registros;
create policy "Usuarios autenticados pueden eliminar registros"
on public.registros for delete
to authenticated
using (true);

-- El acceso a la app se gestiona desde Authentication > Users.
-- No hay registro público: solo podrán entrar los usuarios que crees allí.
