
-- Registro Pirulo 4.2 — usuarios, administración y actividad
-- Ejecutar una sola vez en Supabase > SQL Editor.
-- Este script NO borra los registros existentes.

-- 1) Perfiles de usuarios y roles
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  role text not null default 'consulta' check (role in ('admin','produccion','consulta')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  last_login_at timestamptz
);

-- 2) Historial de actividad
create table if not exists public.activity_log (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  action text not null,
  entity_type text default '',
  entity_id bigint,
  detail text default '',
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.activity_log enable row level security;
alter table public.registros enable row level security;

-- 3) Función segura para comprobar administrador
create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid()
      and role = 'admin'
      and active = true
  );
$$;

-- 4) Crear perfil automáticamente para nuevos usuarios
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id,email,role,active)
  values (new.id, coalesce(new.email,''), 'consulta', true)
  on conflict (id) do update set email = excluded.email;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- 5) Crear perfiles para usuarios existentes.
insert into public.profiles (id,email,role,active)
select id, coalesce(email,''), 'consulta', true
from auth.users
on conflict (id) do update set email = excluded.email;

-- El primer usuario existente queda como administrador.
update public.profiles
set role='admin', active=true
where id = (select id from auth.users order by created_at asc limit 1);

-- 6) REGISTROS: solo usuarios autenticados
drop policy if exists "Usuarios autenticados pueden ver registros" on public.registros;
drop policy if exists "Usuarios autenticados pueden crear sus registros" on public.registros;
drop policy if exists "Usuarios autenticados pueden editar registros" on public.registros;
drop policy if exists "Usuarios autenticados pueden eliminar registros" on public.registros;
drop policy if exists "Permitir insertar registros" on public.registros;
drop policy if exists "Permitir leer registros" on public.registros;
drop policy if exists "Permitir actualizar registros" on public.registros;
drop policy if exists "Permitir eliminar registros" on public.registros;

create policy "Solo autenticados pueden ver registros"
on public.registros for select to authenticated
using (true);

create policy "Solo autenticados pueden crear registros"
on public.registros for insert to authenticated
with check (user_id = auth.uid());

create policy "Solo autenticados pueden editar registros"
on public.registros for update to authenticated
using (true) with check (true);

create policy "Solo autenticados pueden eliminar registros"
on public.registros for delete to authenticated
using (true);

-- 7) PROFILES
drop policy if exists "Usuarios ven su perfil" on public.profiles;
drop policy if exists "Usuarios actualizan su ultimo acceso" on public.profiles;

create policy "Usuarios ven su perfil"
on public.profiles for select to authenticated
using (id = auth.uid() or public.is_admin());

create policy "Usuarios actualizan su ultimo acceso"
on public.profiles for update to authenticated
using (id = auth.uid() or public.is_admin())
with check (id = auth.uid() or public.is_admin());

-- 8) ACTIVIDAD
drop policy if exists "Usuarios registran su actividad" on public.activity_log;
drop policy if exists "Administradores ven actividad" on public.activity_log;

create policy "Usuarios registran su actividad"
on public.activity_log for insert to authenticated
with check (user_id = auth.uid());

create policy "Administradores ven actividad"
on public.activity_log for select to authenticated
using (public.is_admin());

-- 9) Permisos: quitamos acceso anónimo y dejamos solo autenticados.
revoke all on table public.registros from anon;
revoke all on table public.profiles from anon;
revoke all on table public.activity_log from anon;

grant usage on schema public to authenticated;
grant select, insert, update, delete on table public.registros to authenticated;
grant select, update on table public.profiles to authenticated;
grant select, insert on table public.activity_log to authenticated;
grant usage, select on all sequences in schema public to authenticated;


-- 10) HISTORIAL / GIRAS 4.3
create table if not exists public.historial_giras (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  visit_date date not null,
  city text not null,
  place_id bigint references public.registros(id) on delete set null,
  activity text default '',
  notes text default '',
  created_at timestamptz not null default now()
);

alter table public.historial_giras enable row level security;
drop policy if exists "Usuarios autenticados pueden ver historial" on public.historial_giras;
drop policy if exists "Usuarios autenticados pueden crear historial" on public.historial_giras;
drop policy if exists "Usuarios autenticados pueden editar historial" on public.historial_giras;
drop policy if exists "Usuarios autenticados pueden eliminar historial" on public.historial_giras;
create policy "Usuarios autenticados pueden ver historial" on public.historial_giras for select to authenticated using (true);
create policy "Usuarios autenticados pueden crear historial" on public.historial_giras for insert to authenticated with check (user_id = auth.uid());
create policy "Usuarios autenticados pueden editar historial" on public.historial_giras for update to authenticated using (true) with check (true);
create policy "Usuarios autenticados pueden eliminar historial" on public.historial_giras for delete to authenticated using (true);
revoke all on table public.historial_giras from anon;
grant select, insert, update, delete on table public.historial_giras to authenticated;
grant usage, select on sequence public.historial_giras_id_seq to authenticated;
